### ISSUE TITLE
Impressum erstellen

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Babykarte#2]
Impressum, von Website verlinkt (Footer oder Header)

**Comment by Discostu36** [comment]
I have created one. It still needs to be integrated into the internationalization.

**Comment by ValorNaram** [comment]
Now internationalized.

**Comment by Discostu36** [comment]
Link from German version of the site leads to the English Impressum.

**Comment by ValorNaram** [comment]
As you might see there is no extra site for the English Impressum. It's powered by my language system I've written specially for Babykarte. The site on `impress.html` forces my script to use the language the user has selected as his/her default.

**Comment by Discostu36** [comment]
Default as in browser settings or default as in language selection on the website?

**Comment by ValorNaram** [comment]
default as in browser setting

**Comment by Discostu36** [comment]
Doesn't work, my browser is set to German but Impressum is displayed in English. Is it possible to show the site in the language that was selected for the map without using cookies?

**Comment by ValorNaram** [comment]
**Now implemented, repo updated**
