### ISSUE TITLE
shop=clothes doesn't work

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/Babykarte#28]
The query for shop=clothes is broken, I tried to fix it myself but don't get it to work.

**Comment by ValorNaram** [comment]
It seems it's not mapped this way. Shop must include `shop=clothes` and `clothes=babies` or `clothes=children`

**Comment by Discostu36** [comment]
No, the query is the problem, not the mapping. It seems that pipe symbol for "or" doesn't work.

**Working query (without coordinates):**
`[out:json][timeout:25];(node["shop"="clothes"]["clothes"="children"];way["shop"="clothes"]["clothes"="children"];relation["shop"="clothes"]["clothes"="children"];node["clothes"="babies"];way["clothes"="babies"];relation["clothes"="babies"];);out;>;out skel qt;`

**Comment by ValorNaram** [comment]
weird. I will try to fix that

**Comment by ValorNaram** [comment]
Solved. Was just a little mistake I've made due to my misinterpretations of the Overpass laanguage.

**Going to close this issue now**
